#!/usr/bin/env python

import sys
from vcsrosetta import print_translated_usage

def main():
    args = sys.argv[1:]
    if len(args) == 0:
        print("""
            usage: g2h [command] [args]

            example: g2h checkout
        """)
        return
    elif args[0] == 'git':
        # strip the git command off the args list
        args = args[1:]
    print_translated_usage.main(from_type = 'git', to_type = 'hg', args = args)

if __name__ == "__main__":
    main()
