#!/usr/bin/env python

import sys
from translator import print_translated_usage

def main():
    print_translated_usage.main(from_type = 'git', to_type = 'hg', args = sys.argv[1:])
    
if __name__ == "__main__":
    main()
