#!/usr/bin/env python

import sys
from vcsrosetta import print_translated_usage

def main():
    print_translated_usage.main(from_type = 'hg', to_type = 'git', args = sys.argv[1:])

if __name__ == "__main__":
    main()
