#!/usr/bin/env python

import sys
from vcsrosetta import print_translated_usage


def main():
    args = sys.argv[1:]
    if len(args) == 0:
        print("""
            usage: h2g [command] [args]

            example: hg2 checkout
        """)
        return
    elif args[0] == 'hg':
        # strip the git command off the args list
        args = args[1:]
    print_translated_usage.main(from_type='hg', to_type='git', args=args)


if __name__ == "__main__":
    main()
